### PR TITLE
test only acc test

### PR DESCRIPTION
**Pull request by liu-sheng**

### CODE REVIEW

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-acceptance-test http://80.158.20.68/logs/2/2/413199ed8b2b215938d35df2f16f002f027440b5/check/terraform-acceptance-test/a58bf44/ : TIMED_OUT in 1h 00m 50s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-acceptance-test http://80.158.20.68/logs/2/2/413199ed8b2b215938d35df2f16f002f027440b5/check/terraform-acceptance-test/5e03881/ : TIMED_OUT in 1h 00m 47s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-acceptance-test http://80.158.20.68/logs/2/2/413199ed8b2b215938d35df2f16f002f027440b5/check/terraform-acceptance-test/85735c2/ : TIMED_OUT in 1h 00m 48s

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
Build failed.

- terraform-acceptance-test http://80.158.20.68/logs/2/2/413199ed8b2b215938d35df2f16f002f027440b5/check/terraform-acceptance-test/559de3f/ : TIMED_OUT in 1h 00m 48s

**Comment by liu-sheng** [comment]
recheck

**Comment by kiwik** [comment]
Close the test PR.

**Pull request closed without merging**
